name: kibamail

services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kibamail

  clickhouse:
    environment:
      CLICKHOUSE_DB: kibamail

volumes:
  mysql_data:
    name: mysql_dev_data
