services:
  mysql:
    image: mysql:latest
    ports:
      - "5567:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  clickhouse:
    image: clickhouse/clickhouse-server:24.7.3-alpine
    ports:
      - "5568:8123"
      - "5569:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_USER: kibamail

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - "5570:6379"
    volumes:
      - redis_data:/data

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 5571:8025
      - 25:1025
    environment:
      MP_MAX_MESSAGES: 500000
      MP_SMTP_DISABLE_RDNS: true
      SMTP_USER: kibamail
      SMTP_PASS: password

  mongodb:
    image: mongo:latest
    ports:
      - "5573:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mysql_data:
  clickhouse_data:
  redis_data:
  mongodb_data:
