services:
  dnsmasq:
    build:
      context: ./dnsmasq
      dockerfile: dnsmasq.dockerfile
    container_name: dnsmasq
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.2
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "5567:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.3

  clickhouse:
    image: clickhouse/clickhouse-server:24.7.3-alpine
    container_name: clickhouse
    ports:
      - "5568:8123"
      - "5569:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_USER: kibamail
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.4

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "5570:6379"
    volumes:
      - redis_data:/data
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.5

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 5571:1025
      - 5572:8025
    environment:
      MP_MAX_MESSAGES: 500000
      MP_SMTP_DISABLE_RDNS: true
      SMTP_USER: kibamail
      SMTP_PASS: password
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.6

  smtp_proxy:
    image: nginx:alpine
    container_name: smtp_proxy
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.7
    ports:
      - "25:25"
    volumes:
      - ./dnsmasq/nginx.conf:/etc/nginx/nginx.conf

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: on-failure
    entrypoint: sh
    command: -c ' mkdir -p /data/attachments && mkdir -p /data/emails && mkdir -p /data/contacts && minio  server /data --console-address ":9001"'
    environment:
      - MINIO_ROOT_USER=c7p5jgfcze6qxpidordkdkjzw3cjnq
      - MINIO_ROOT_PASSWORD=35jids3f4ze6qxpidordkd7owed7gzk6dgsca
    ports:
      - "5590:9000"
      - "5591:9001"
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.9

volumes:
  mysql_data:
  clickhouse_data:
  redis_data:

networks:
  kibamail-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
