services:
  dnsmasq:
    build:
      context: ./dnsmasq
      dockerfile: dnsmasq.dockerfile
    container_name: dnsmasq
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.2
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf

  mysql:
    image: mysql:latest
    ports:
      - "5567:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.3

  clickhouse:
    image: clickhouse/clickhouse-server:24.7.3-alpine
    ports:
      - "5568:8123"
      - "5569:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: password
      CLICKHOUSE_USER: kibamail
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.4

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - "5570:6379"
    volumes:
      - redis_data:/data
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.5

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 5571:1025
      - 5572:8025
    environment:
      MP_MAX_MESSAGES: 500000
      MP_SMTP_DISABLE_RDNS: true
      SMTP_USER: kibamail
      SMTP_PASS: password
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.6

  mongodb:
    image: mongo:latest
    ports:
      - "5573:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.7

  smtp_proxy:
    image: nginx:alpine
    container_name: smtp_proxy
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.8
    ports:
      - "25:25"
    volumes:
      - ./dnsmasq/nginx.conf:/etc/nginx/nginx.conf

  haraka:
    build:
      context: ..
      dockerfile: docker/haraka.dockerfile
    container_name: haraka
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.9
    dns:
      - 172.20.0.2
    ports:
      - "1025:587"
    volumes:
      - ../src/haraka:/app/haraka

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: gmaaail.com
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.10
    dns:
      - 172.20.0.2
    ports:
      - "5580:25"
      - "5581:465"
      - "5582:587"
      - "5583:143"
      - "5584:993"
    volumes:
      - ./mailserver/mail-data/:/var/mail/
      - ./mailserver/mail-state/:/var/mail-state/
      - ./mailserver/mail-logs/:/var/log/mail/
      - ./mailserver/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    stop_grace_period: 1m
    restart: always

  rspamd:
    image: rspamd/rspamd:latest
    container_name: rspamd
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.11
    ports:
      - "11333:11333"
    volumes:
      - rspamd_data:/var/lib/rspamd
    restart: unless-stopped

  spamassassin:
    image: axllent/spamassassin:latest
    container_name: spamassassin
    networks:
      kibamail-network:
        ipv4_address: 172.20.0.12
    ports:
      - "5587:783"
    restart: unless-stopped
    environment:
      - DNS_CHECKS=true

volumes:
  mysql_data:
  clickhouse_data:
  redis_data:
  mongodb_data:
  rspamd_data:

networks:
  kibamail-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
