name: kibamail

services:
  dnsmasq:
    build:
      context: ./dnsmasq
      dockerfile: dnsmasq.dockerfile
    container_name: dnsmasq
    networks:
      default:
        ipv4_address: 172.20.0.2
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf

  pd0:
    image: pingcap/pd:nightly
    container_name: tidb-pd
    ports:
      - "2379"
    volumes:
      - ./tidb/config/pd-nightly-tiflash.toml:/pd.toml:ro
      - ./tidb/data:/data
      - ./tidb/logs:/logs
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
      - --data-dir=/data/pd
      - --config=/pd.toml
      - --log-file=/logs/pd.log
    restart: on-failure

  tikv:
    image: pingcap/tikv:nightly
    container_name: tidb-kv
    volumes:
      - ./tidb/data:/data
      - ./tidb/logs:/logs
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv:20160
      - --status-addr=tikv:20180
      - --data-dir=/data/tikv
      - --pd=pd0:2379
      - --log-file=/logs/tikv.log
    depends_on:
      - "pd0"
    restart: on-failure

  tidb:
    image: pingcap/tidb:nightly
    container_name: tidb
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./tidb/logs:/logs
      - ./tidb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    command:
      - --status=10080
      - --advertise-address=tidb
      - --store=tikv
      - --path=pd0:2379
      - --log-file=/logs/tidb.log
    depends_on:
      - "tikv"
    restart: on-failure

  tiflash:
    image: pingcap/tiflash:nightly
    container_name: tidb-flash
    volumes:
      - ./tidb/config/tiflash-nightly.toml:/tiflash.toml:ro
      - ./tidb/config/tiflash-learner-nightly.toml:/tiflash-learner.toml:ro
      - ./tidb/data:/data
      - ./tidb/logs:/logs
    command:
      - --config=/tiflash.toml
    depends_on:
      - "tikv"
      - "tidb"
    restart: on-failure

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "5567:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kibamail
    networks:
      default:
        ipv4_address: 172.20.0.3

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "5570:6379"
    volumes:
      - redis_data:/data
    networks:
      default:
        ipv4_address: 172.20.0.5

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: on-failure
    entrypoint: sh
    command: -c ' mkdir -p /data/attachments && mkdir -p /data/emails && mkdir -p /data/contacts && minio  server /data --console-address ":9001"'
    environment:
      - MINIO_ROOT_USER=c7p5jgfcze6qxpidordkdkjzw3cjnq
      - MINIO_ROOT_PASSWORD=35jids3f4ze6qxpidordkd7owed7gzk6dgsca
    ports:
      - "5590:9000"
      - "5591:9001"
    networks:
      default:
        ipv4_address: 172.20.0.9

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 5571:1025
      - 5572:8025
    environment:
      MP_MAX_MESSAGES: 500000
      MP_SMTP_DISABLE_RDNS: true
      SMTP_USER: kibamail
      SMTP_PASS: password
    dns: 172.20.0.2
    networks:
      default:
        ipv4_address: 172.20.0.6

  smtp_proxy:
    image: nginx:alpine
    container_name: smtp_proxy
    networks:
      default:
        ipv4_address: 172.20.0.13
    dns: 172.20.0.2
    ports:
      - "25:25"
    volumes:
      - ./dnsmasq/nginx.conf:/etc/nginx/nginx.conf

  kumomta-sink:
    container_name: kumomta-sink
    hostname: sinkinator
    image: ghcr.io/kumocorp/kumomta-dev:latest
    volumes:
      - ./kumomta/policy:/opt/kumomta/etc/policy
    restart: unless-stopped
    ports:
      - 5610:25
      - 5611:8000
    networks:
      default:
        ipv4_address: 172.20.0.10

  kumomta-dev:
    container_name: kumomta-dev
    hostname: kumomta-dev
    image: ghcr.io/kumocorp/kumomta-dev:latest
    volumes:
      - ../src/kumomta/policy:/opt/kumomta/etc/policy
      - ./kumomta/data:/var/log/kumomta
      - ./kumomta/spool:/var/spool/kumomta
    restart: unless-stopped
    dns: 172.20.0.2
    environment:
      API_HTTP_ACCESS_TOKEN: tSv1rimOykRimRB7XgLtYDctSv1rimOykRimRB7XgLtYDc
      API_HTTP_SERVER: "http://host.docker.internal:5566"
    ports:
      - 5612:25
      - 5613:8000
    networks:
      default:
        ipv4_address: 172.20.0.11

volumes:
  mysql_data:
    name: kibamail_mysql
  redis_data:
    name: kibamail_redis

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
