version: 2.1

jobs:
  build_and_test:
    docker:
      - image: node:22  # Using Node.js 22
    steps:
      - checkout
      - run:
          name: "Start development environment"
          command: |
            make dev
      - run:
          name: Wait for services to start
          command: sleep 5
      - run:
          name: Install dependencies
          command: pnpm install
      - run:
          name: Run tests
          command: pnpm test

workflows:
  version: 2
  build_test_workflow:
    jobs:
      - build_and_test
